name: Debug Filstruktur

on:
  workflow_dispatch:  # Tillåter endast manuell körning

jobs:
  debug-file-structure:
    name: Debugga filstruktur
    runs-on: ubuntu-latest
    
    steps:
      - name: Checka ut koden
        uses: actions/checkout@v3
      
      - name: Lista alla filer och kataloger
        run: |
          echo "Lista över alla filer och kataloger i repository:"
          find . -type f -name "*.bicep" | sort
          
          echo "--------------------------------------------"
          echo "Detaljerad katalogstruktur:"
          ls -la
          
          echo "--------------------------------------------"
          echo "Innehåll i azure-deployment (om den finns):"
          if [ -d "azure-deployment" ]; then
            ls -la azure-deployment
            echo "--------------------------------------------"
            echo "Innehåll i azure-deployment/modules (om den finns):"
            if [ -d "azure-deployment/modules" ]; then
              ls -la azure-deployment/modules
            else
              echo "Katalogen azure-deployment/modules finns inte!"
            fi
          else
            echo "Katalogen azure-deployment finns inte!"
          fi
          
          echo "--------------------------------------------"
          echo "Sök efter alla networking.bicep filer:"
          find . -name "networking.bicep" -type f
          
          echo "--------------------------------------------"
          echo "Aktuell arbetskatalog:"
          pwd
